---
title: "Mucoviscidose"
output:
  pdf_document:
    latex_engine: xelatex
linkcolor: blue
---


# Contexte des données

Les données du fichier cystfibr.dat concernent la fonction respiratoire de patients atteints de
fibrose kystique (aussi appelée mucoviscidose). Ces données ont été mesurées sur 25 patients de 7 à 23 ans.


# Descriptif des données

10 colonnes et 25 lignes:

Nom de la colonne      | Type de variable     | Description
--------               | ----------           | --------------------------------------
`age`                  | Nombre entier        | Âge en années
`sex`                  | Nombre entier        | Genre (`0` = femme, `1` = homme)
`height`               | Nombre entier        | Taille en cm
`weight`               | Nombre réel          | Poids en kg
`bmp`                  | Nombre entier        | Masse corporelle en proportion de la masse normale
`fev1`                 | Nombre entier        | Volume expiratoire forcé en 1 seconde (en proportion de la normale)
`rv`                   | Nombre entier        | Volume résiduel (= volume d'air restant dans les poumons ne pouvant pas être expiré)
`frc`                  | Nombre entier        | Capacité résiduelle fonctionnelle (= volume d'air pouvant être expiré)
`tlc`                  | Nombre entier        | Capacité pulmonaire totale (= volume totale des poumons)
`pemax`                | Nombre entier        | Pression maximale à l’expiration (en cm d'H2O)


# Travail demandé

## Objectifs

Plusieurs études peuvent être envisagées :

- On pourra chercher à comprendre l’influence des variables dans la variance de la population
en général, c’est à dire à identifier les variables pertinentes qui permettent de séparer
des groupes.
- On s’intéressera aussi aux facteurs qui influent sur la pemax.
- On pourra enfin chercher à prédire la pemax en fonction des résulats obtenus dans les
points précédents.
Les techniques pouvant être utilisée dans le cadre de cette étude sont principalement l’ACP,
les modèles linéaires, l’ANOVA. Dans le cadre de la recherche de groupes homogènes vis-à-vis
de la pemax, le kmeans pourra être employé, ou encore la régression logistique.


## Exercice à rendre

Vous présenterez vos résultats lors de la dernière séance le 4 avril : 20 minutes de présentation
et 10 minutes de questions.
Votre présentation devra comporter les parties suivantes :

- Présentation du contexte et de la question que vous souhaitez poser et répondre
- Présentation de vos données
- Présentation de la méthode choisie (pourquoi cette méthode, expliquez succinctement
son fonctionnement)
- Présentation des résultats
- Conclusion




# Références

D.G. Altman (1991), Practical Statistics for Medical Research, Table 12.11, Chapman Hall.

O’Neill et al. (1983), The effects of chronic hyperinflation, nutritional status, and posture on
respiratory muscle strength in cystic fibrosis, Am. Rev. Respir. Dis., 128 :1051–1054.*
